root = "."
tmp_dir = "tmp"

[build]
 pre_cmd = ["templ generate"]
cmd = "go build -o ./tmp/exchange internal/main.go"
bin = "tmp/exchange"
include_ext = ["go", "temp"]
exclude_regex = ["_test.go"]
exclude_unchanged = true
stop_on_error = true

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true

[screen]
clear_on_rebuild = true
keep_scroll = true
